package com.f.chapter12.exception_;

public class Exception_ {
    public static void main(String[] args) {
        int num1 = 10, num2 = 0;
        try {
            System.out.println(num1/num2);
        } catch (Exception e) {
            System.out.println("³ýÊýÎª0");
        }
    }
}

